@startuml

entity User {
    * user_id: ObjectId
    * name: String
    * email: String
    * password: String
    * phone_number String
    * account_type String
    * orders <ListOfOrders>: Array
}

entity  ListOfOrders_address {
    * country: String
    * region: String
    * street: String
    * house_number: Integer
    * apartment_number: Integer
}

entity ListOfOrders {
    * order_id: ObjectId
    * user_id: ObjectId
    * total_price: Decimal
    * order_date: Date
    * status: String
    * address: Object
    * cart: Object
    * payment: Object
}

entity ListOfProducts {
    * product_id: ObjectId
    * name: String
    * description: String
    * price: Decimal
    * stock_quantity: Integer
    * category: Object
}

entity ListOfOrders_cart {
    * products <ListOfProducts>: Array
    * amount: Integer
    * unit_price: Decimal
    * subtotal: Decimal
}

entity ListOfOrders_payment {
    * payment_id: ObjectId
    * order_id: ObjectId
    * amount: Decimal
    * status: String
    * payment_method: String
    * transaction_id: String
    * payment_date: Date
}

entity ListOfProducts_category {
    * _id: ObjectId
    * name: String
    * description: String
}


User ||--o{ ListOfOrders
ListOfOrders ||--|| ListOfOrders_address
ListOfOrders ||--|| ListOfOrders_cart
ListOfOrders_cart ||--o{ ListOfProducts
ListOfOrders ||--|| ListOfOrders_payment
ListOfProducts_category ||--|{ ListOfProducts


@enduml
