@startuml C4_Container
!include <C4/C4_Container>

Person(personAlias, "Клиент", "Заказывает товары через систему")
Person(personAlias1, "Продавец", "Продает товары клиенту")
Person(personAlias2, "Администратор", "Проверка на выполнение условий Leroy Merlin")

System_Boundary(systemAlias, "Система заказа товара") {
    Container(mobile, "Мобильное приложение", "Kotlin", "Предоставляет пользователям доступ к мобильному приложению")
    Container(web, "Веб приложение", "JavaScript", "Предотсавляет пользователям доступ к сайту")
    Container(gatewayWeb, "Web API gateway", "Java", "Осуществялет связь с сервисами")
    Container(gatewayMobile, "Mobile API gateway", "Java", "Осуществялет связь с сервисами")
    Container(order, "Сервис заказа", "Java", "Создание заказов, управление состояниями заказов, расчет стоимости")
    Container(inventory, "Сервис складской логистики", "Java", "Управление запасами, отслеживание остатков на складах, инвентаризация")
    Container(delivery, "Сервис доставки", "Java", "Расчёт стоимости доставки, планирование маршрутов, отслеживание статуса доставки")
    Container(user, "Сервис управления пользователями", "Java", "Регистрация, аутентификация, профили пользователей, управление правами доступа")
    Container(cart, "Сервис управления корзиной", "Java", "Предотсавляет возможность собрать товары в корзину для дальнейшей оплаты")
    Container(shluzExt1, "Шлюз 5", "Java", "Обеспечивает взаимодействие с внешней системой складского учета")
    ContainerQueue(queue, "Брокер", "Apache Kafka", "Очередь заказов на оплату")
    Container(shluz, "Шлюз 1", "Java", "Обеспечивает взаимодействие с системами интернет-платежей")
    ContainerDb(database1, "База данных 1", "PostgreSQL", "Хранение пользовательских данных")
    Container(shluz2, "Шлюз 2", "Java", "Обеспеичвает взаимодействие БД")
    Container(shluz3, "Шлюз 3", "Java", "Обеспеичвает взаимодействие БД")
    Container(shluzExt2, "Шлюз 6","Java", "Обеспечивает взаимодействие с внешней системой доставки")
    ContainerDb(database2, "База данных 2", "PostgreSQL", "Хранение товаров")
    ContainerDb(database3, "База данных 3", "PostgreSQL", "Корзина товаров")
    ContainerDb(database4, "База данных 4", "PostgreSQL", "Хранение информации платежей")
    ContainerDb(database5, "База данных 5", "PostgreSQL", "Хранение информации о пути доставки")
}

System_Ext(payAlias, "Система оплаты", "Обеспечивает работу интернет платежей")
System_Ext(deliveryAlias, "Система доставки через партнеров", "Взаимодействие с курьерскими службами и транспортными компаниями")
System_Ext(wAlias, "Система складского учета поставщиков", "Получение данных о наличии и движении товаров на складах поставщиков")


Rel(personAlias, mobile, "Просматривает и делает заказ")
Rel(personAlias, web, "Просматривает и делает заказ")
Rel(personAlias1, mobile, "Передает товар на склад и создает страничку товара в сервисе")
Rel(personAlias1, web, "Передает товар на скл ад и создает страничку товара в сервисе")
Rel(personAlias2, mobile, "Вносит правки")
Rel(personAlias2, web, "Вносит правки")
Rel(mobile, gatewayMobile, "REST API", "JSON/HTTPs")
Rel(web, gatewayWeb, "REST API", "JSON/HTTPs")
Rel(gatewayWeb, order, "REST API", "JSON/HTTPs")
Rel(gatewayWeb, inventory, "REST API", "JSON/HTTPs")
Rel(gatewayWeb, delivery, "REST API", "JSON/HTTPs")
Rel(gatewayWeb, user, "REST API", "JSON/HTTPs")
Rel(gatewayWeb, cart, "REST API", "JSON/HTTPs")
Rel(gatewayMobile, order, "REST API", "JSON/HTTPs")
Rel(gatewayMobile, inventory, "REST API", "JSON/HTTPs")
Rel(gatewayMobile, delivery, "REST API", "JSON/HTTPs")
Rel(gatewayMobile, user, "REST API", "JSON/HTTPs")
Rel(gatewayMobile, cart, "REST API", "JSON/HTTPs")

Rel(inventory, shluzExt1, "Запрашивает информацию о товарах", "REST API JSON/HTTPs")
Rel(delivery, shluzExt2, "Запрашивает информацию о доставке через партнеров", "REST API JSON/HTTPs")
Rel(shluzExt2, deliveryAlias, "Отправляет запросы на получение данных с доставке через партнеров", "REST API JSON/HTTPs")
BiRel(user, database1, "Чтение и запись")
Rel(cart, database3, "Чтение")
BiRel(inventory, database2, "Чтение и запись")
Rel(order, queue, "Формирует запрос на оплату", "Kafka")
Rel(queue, shluz, "Передает запрос на оплату", "Kafka")
Rel(shluz, database4, "Запись в базу данных")
Rel_L(database4, shluz2, "Запрос информации о платежах")
Rel(shluz2, database1, "Чтение")
Rel_L(shluz, payAlias, "Отправляет запросы на оплату", "REST API JSON/HTTPs")
Rel_D(database2, shluz3, "Запрос информации о товарах")
Rel(shluz3, database3, "Запись")
BiRel(delivery, database5, "Чтение и запись")
Rel_D(database5, shluz2, "Запрос информации о доставке")
Rel(shluzExt1, wAlias, "Отправляет запросы на получение данных с внешних складов", "REST API JSON/HTTPs")   


SHOW_LEGEND()
@enduml 