@startuml C4_Context
!include <C4/C4_Container>

Person(personAlias, "Клиент", "Заказывает товары через систему")
Person(personAlias1, "Продавец", "Продает товары клиенту")
Person(personAlias2, "Администратор", "Проверка на выполнение условий")
System(systemAlias, "Система заказа товара", "Обработка заказа")
System_Ext(payAlias, "Система оплаты", "Обеспечивает работу интернет платежей")
System_Ext(deliveryAlias, "Система доставки через партнеров", "Взаимодействие с курьерскими службами и транспортными компаниями")
System_Ext(wAlias, "Система складского учета поставщиков", "Получение данных о наличии и движении товаров на складах поставщиков")

Rel(personAlias, systemAlias, "Просматривает и делает заказ")
Rel(personAlias1, systemAlias, "Передает товар на склад и создает страничку товара в сервисе")
Rel(personAlias2, systemAlias, "Вносит правки")
Rel(systemAlias, payAlias, "Запрос на обработку платежа")
Rel(systemAlias, deliveryAlias, "Отправка данных о заказах для оформления доставки")
Rel(systemAlias, wAlias, "Запрос информации о наличии товаров и обновление статуса запасов")
@enduml